name: Flutter CI

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '12'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Pub Get
        run: flutter pub get
      
      - name: Buid APK
        run: flutter build apk
        
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: learn2learn ${{github.ref_name}}
          files: |
            build/app/outputs/apk/release/app-release.apk
